# Generated by Django 6.0.7 on 2026-08-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
