"""
Django settings for smartai project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
from dotenv import load_dotenv
import os


BASE_DIR = Path(__file__).resolve().parent.parent


load_dotenv(BASE_DIR / ".env")



GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

MAGIC_HOUR_API_KEY = os.getenv("MAGIC_HOUR_API_KEY")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")


SECRET_KEY = (
    "django-insecure-&9j*5%1nvtf-o=5&m2^&ps%%xg5mfcm49"
    "$6slmh$97ob7nf7-s"
)

DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Django Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    # Google OAuth
    "allauth.socialaccount.providers.google",

    # Your application
    "accounts",
]


MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # Allauth
    "allauth.account.middleware.AccountMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]



ROOT_URLCONF = "smartai.urls"


TEMPLATES = [

    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates"
        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],
        },
    },
]



WSGI_APPLICATION = "smartai.wsgi.application"


DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",

    }
}


AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "/dashboard/"

LOGOUT_REDIRECT_URL = "/login/"


SOCIALACCOUNT_PROVIDERS = {

    "google": {

        "APPS": [

            {
                "client_id": GOOGLE_CLIENT_ID,

                "secret": GOOGLE_CLIENT_SECRET,

                "key": "",
            },

        ],

        "SCOPE": [

            "profile",

            "email",

        ],

        "AUTH_PARAMS": {

            "access_type": "online",

        },

        "OAUTH_PKCE_ENABLED": True,
    },
}


SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True

SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True


ACCOUNT_LOGIN_METHODS = {
    "email",
}


ACCOUNT_SIGNUP_FIELDS = [

    "email*",

    "password1*",

    "password2*",

]


SECURE_SSL_REDIRECT = False

SESSION_COOKIE_SECURE = False

CSRF_COOKIE_SECURE = False